### ISSUE TITLE
upper MFD not working

### ISSUE THREAD

**Issue by trschnitzel** [Horizon-Simulations/HS-B787-9#67]
as you could see in the picture the upper MFD shows 2 green. I cannot choose left or right. I cannot shutdown the green lights. Any idea? Thanks!
![787 mfd](https://github.com/Horizon-Simulations/HS-B787-9/assets/81495314/8041d1ad-fb30-4933-80fe-d2b50a44e441)

**Comment by DerbeQ** [comment]
The last time I checked, it worked fine. You could switch from L and R MFD.

**Comment by trschnitzel** [comment]
nice for you!

**Comment by markszutor** [comment]
On our end it is functioning as it should. If you're having issues then it might be time to look at some tutorials online as to how to use the displays and other features on the 787.

https://www.youtube.com/watch?v=qyxgynizMK8&t=2267s

**Comment by markszutor** [comment]
Closing this issue as resolved.

**Comment by trschnitzel** [comment]
maybe i should deinstall and reinstall??? but how do i deinstall, so all files are delited?
